version: "2.0"
services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile-web
    image: shopmates-web:latest
    container_name: s-web
    restart: always
    ports:
      - "37580:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - web-api
  
  web-admin:
    build: 
      context: .
      dockerfile: Dockerfile-Admin
    image: shopmates-webadmin:latest
    container_name: s-webadmin
    restart: always
    ports:
      - "37362:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - user-content:/app/wwwroot/user-content
    depends_on:
      - web-api
      
  web-api:
    build: 
      context: .
      dockerfile: Dockerfile-API
    image: shopmates-api:latest
    container_name: s-webapi
    restart: always
    ports:
      - "37354:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - user-content:/app/wwwroot/user-content

volumes:
  user-content:
    external: true