version: "2.0"
services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile-web
    image: shopmates-web
    container_name: s-web
    ports:
      - "37580:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - web-api
  
  web-admin:
    build: 
      context: .
      dockerfile: Dockerfile-Admin
    image: shopmates-webadmin
    container_name: s-webadmin
    ports:
      - "37362:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - web-api
      
  web-api:
    build: 
      context: .
      dockerfile: Dockerfile-API
    image: shopmates-api
    container_name: s-webapi
    ports:
      - "37372:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development